import { GoogleSpreadsheet } from 'google-spreadsheet'
import {google} from 'googleapis';
const sheets = google.sheets('v4');
export let auth
export let doc
export async function koneksiExcel(){
	// Initialize the sheet - doc ID is the long id in the sheets URL
	
	doc = new GoogleSpreadsheet('1tVw4qmPoqEP_SKkVqz5EukgeDCzoVMItw8TtgdY4ef8');
	
	// Initialize Auth - see https://theoephraim.github.io/node-google-spreadsheet/#/getting-started/authentication
	await doc.useServiceAccountAuth({
	  // env var values are copied from service account credentials generated by google
	  // see "Authentication" section in docs for more info
	  client_email: process.env.client_email,
	  private_key: process.env.private_key,
	});
	
	await doc.loadInfo(); // loads document properties and worksheets
	console.log("berhasil menhubungkan ke document sheet bernama :"+doc.title);

	
	auth = new google.auth.GoogleAuth({
		credentials: {
	     client_email: process.env.client_email,
			private_key: process.env.private_key,
	  },
	  scopes: ['https://www.googleapis.com/auth/spreadsheets']
	});
	return doc
	
}

export async function sheetGetRange(range) {
	let rows
	try {
    
    const response = await sheets.spreadsheets.values.get({
      auth,
      spreadsheetId: '1tVw4qmPoqEP_SKkVqz5EukgeDCzoVMItw8TtgdY4ef8',
      range,
    });
    rows = response.data.values;
    console.log(`Retrieved ${rows.length} rows`);
    console.log(rows);
  } catch (error) {
    console.error(error);
  }
	return rows
	
}


